version: "3.9"
services:
  server:
    image: "nginx:stable"
    restart: always
    volumes:
      # - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on: 
      - app
      - db
  app:
    build: ./
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: db
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - '${DB_PORT:-3306}:${DB_PORT:-3306}'
volumes:
  dbdata:
    driver: local
