version: "3.9"
services:
  server:
    image: "nginx:stable"
    restart: always
    volumes:
      # - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on: 
      - app
      - db
  app:
    build: ./
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: example
      POSTGRES_HOST: db
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  db:
    image: postgres:alpine3.15
    environment:
      POSTGRES_PASSWORD: example
