name: Feature

on:
  push:
    branches:
      - 'feature-test/*'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    uses: ./.github/workflows/_reusable-test.yml
    with:
      environment: test
